# Generated by Django 4.2.3 on 2023-07-27 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventory', '0003_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product_name',
            new_name='name',
        ),
    ]
